###################################
### DIGITAL BANKING 
# app
# no backends
# app agents
#
# Please configure APM related info in .env file
###################################

version: "3.5"
services:

# AGENTE JAVA - APPDYNAMICS
# APM - AGENT VOLUME (SIDECAR)
  appd-agent-saas:
    image: docker.io/appdynamics/java-agent:latest
    container_name: appd-agent
    volumes:
      - agent-volume:/opt/appdynamics


# AGENTE JAVA - OTEL
# APM - AGENT VOLUME (SIDECAR)
  otel-agent-saas:
    image: leandrovo/otel-agent-java:1.20.0
    container_name: otel-java-agent
    volumes:
      - otel-agent-volume:/opt/agent


###################################
#### NGINX - FRONTEND & API
####################################

  nginx:
    image: nginx_otel:latest
    container_name: nginx
    volumes:
      - type: bind
        source: ./opentelemetry_module-frontend.conf
        target: /opt/opentelemetry_module.conf
      - type: bind
        source: ./default-front.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - bank


########################
# OTel Collector
#######################
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: "--config=/etc/otel-collector-config.yaml ${OTELCOL_ARGS}"
    # Change the "source" path below to swap out collector config files!
    volumes:
      - type: bind
        source: ./otel-collector-config.yaml
        target: /etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
      - "55681:55681" # http



###################################
### DIGITAL BANKING APP - BEGIN
###################################

# =====================================================================
# Digital Broker Service Configuration
# =====================================================================
  broker:
    image: leandrovo/digitalbroker-new:1.0
    container_name: broker
    hostname: broker
    ports:
      - "8161:8161"
      - "61616:61616"
    restart: unless-stopped

# =====================================================================
# Digital Credit Service Configuration
# =====================================================================    
  credit:
    image: leandrovo/digitalcredit-new:1.0
    container_name: credit
    hostname: credit
    environment:

      # Debug Options
      LOGGING_LEVEL_IO_DIGISIC_CREDIT: INFO

      # Digital Broker Connection
      SPRING_ARTEMIS_MODE: native
      SPRING_ARTEMIS_HOST: broker
      SPRING_ARTEMIS_PORT: 61616
      SPRING_ARTEMIS_USER: admin
      SPRING_ARTEMIS_PASSWORD: admin

      # Credit Application Process
      IO_DIGISIC_CREDIT_APP_PROCESS_ENABLED: 'true'
      IO_DIGISIC_CREDIT_APP_PROCESS_TIME: 20

      # Digital Credit Application Process JMS Queues
      IO_DIGISIC_PARTNER_CREDIT_APP_REQUEST: CREDIT.APP.REQUEST
      IO_DIGISIC_PARTNER_CREDIT_APP_RESPONSE: CREDIT.APP.RESPONSE

      #APM AGENT VARIABLES
      JAVA_OPTS: '-javaagent:/opt/appdynamics/javaagent.jar -Dappdynamics.opentelemetry.enabled=true -Dotel.traces.exporter=otlp'
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: service.name=credit,service.namespace=${APPDYNAMICS_AGENT_APPLICATION_NAME}
      APPDYNAMICS_CONTROLLER_HOST_NAME: ${APPDYNAMICS_CONTROLLER_HOST_NAME}
      APPDYNAMICS_CONTROLLER_PORT: ${APPDYNAMICS_CONTROLLER_PORT}
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: ${APPDYNAMICS_CONTROLLER_SSL_ENABLED}
      APPDYNAMICS_AGENT_ACCOUNT_NAME: ${APPDYNAMICS_AGENT_ACCOUNT_NAME}
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: ${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: ${APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME}
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX:  ${APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX}
      APPDYNAMICS_AGENT_APPLICATION_NAME:  ${APPDYNAMICS_AGENT_APPLICATION_NAME}
      APPDYNAMICS_AGENT_TIER_NAME: 'credit'
      APPDYNAMICS_AGENT_NODE_NAME: 'credit-node'      

    depends_on:
      - broker

    #APM - ADD AGENT VOLUME
    volumes:
      - agent-volume:/opt/appdynamics
    restart: unless-stopped      

# =====================================================================
# Digital Bank Service Configuration
# =====================================================================
  bank:
    image: leandrovo/digitalbank-new:1.0
    container_name: bank
    hostname: bank
    environment:

      # Debug Options
      LOGGING_LEVEL_IO_DIGISIC_BANK: INFO
      
      # Digital Broker connection
      SPRING_ARTEMIS_MODE: native
      SPRING_ARTEMIS_HOST: broker
      SPRING_ARTEMIS_PORT: 61616
      SPRING_ARTEMIS_USER: admin
      SPRING_ARTEMIS_PASSWORD: admin

      # Digital Credit Connection
      IO_DIGISIC_CREDIT_ENABLED: 'true'
      IO_DIGISIC_CREDIT_PROTOCOL: http
      IO_DIGISIC_CREDIT_HOST: credit
      IO_DIGISIC_CREDIT_PORT: 8080
      IO_DIGISIC_CREDIT_CONTEXT-PATH: /credit
      IO_DIGISIC_CREDIT_USERNAME: admin@demo.io
      IO_DIGISIC_CREDIT_PASSWORD: Demo123!

      # Digital Credit Application Process JMS Queues
      IO_DIGISIC_PARTNER_CREDIT_APP_REQUEST: CREDIT.APP.REQUEST
      IO_DIGISIC_PARTNER_CREDIT_APP_RESPONSE: CREDIT.APP.RESPONSE

      # ATM Location Service Connection 
      IO_DIGISIC_BANK_ATM_PROTOCOL: http
      IO_DIGISIC_BANK_ATM_HOST: atm-search
      IO_DIGISIC_BANK_ATM_PORT: 8081

      # VISA Direct Payment Service
      IO_DIGISIC_BANK_VISA_PROTOCOL: http
      IO_DIGISIC_BANK_VISA_HOST: visa
      IO_DIGISIC_BANK_VISA_PORT: 8081
      
      # Open Banking API Service
      IO_DIGISIC_BANK_OBP_ENABLED: 'true'
      IO_DIGISIC_BANK_OBP_CONSUMER_KEY: vwfpvwfr1kngt0up2jelebzmvxrhst4vhxvw1jm3
      IO_DIGISIC_BANK_OBP_VERSION: v4.0.0
      IO_DIGISIC_BANK_OBP_PROTOCOL: https
      IO_DIGISIC_BANK_OBP_HOST:
      IO_DIGISIC_BANK_OBP_PORT:

      #APM AGENT VARIABLES
      JAVA_OPTS: '-javaagent:/opt/appdynamics/javaagent.jar -Dappdynamics.opentelemetry.enabled=true -Dotel.traces.exporter=otlp'
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: service.name=bank,service.namespace=${APPDYNAMICS_AGENT_APPLICATION_NAME}
      APPDYNAMICS_CONTROLLER_HOST_NAME: ${APPDYNAMICS_CONTROLLER_HOST_NAME}
      APPDYNAMICS_CONTROLLER_PORT: ${APPDYNAMICS_CONTROLLER_PORT}
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: ${APPDYNAMICS_CONTROLLER_SSL_ENABLED}
      APPDYNAMICS_AGENT_ACCOUNT_NAME: ${APPDYNAMICS_AGENT_ACCOUNT_NAME}
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: ${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: ${APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME}
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX:  ${APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX} 
      APPDYNAMICS_AGENT_APPLICATION_NAME:  ${APPDYNAMICS_AGENT_APPLICATION_NAME}
      APPDYNAMICS_AGENT_TIER_NAME: 'bank'
      APPDYNAMICS_AGENT_NODE_NAME: 'bank-node'     

    ports:
      - "8080:8080"

    depends_on:
      - broker
      - credit

    #APM - ADD AGENT VOLUME
    volumes:
      - agent-volume:/opt/appdynamics
    restart: unless-stopped      

###################################
### DIGITAL BANKING APP - END
###################################  

###################################
### DIGITAL BANKING BACKENDS - BEGIN
###################################

  atm-search:
    image: leandrovo/digitalbank-backend-java:1.0
    container_name: backends-atm-java
    ports:
      - "10081:8081"
    environment:
      # zipcode that causes slowdon
      SLOW_ZIP: 14758

      #APM AGENT VARIABLES
      JAVA_TOOL_OPTIONS: '-javaagent:/opt/agent/opentelemetry-javaagent.jar'
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: service.name=atm-search,service.namespace=${APPDYNAMICS_AGENT_APPLICATION_NAME}
      APPDYNAMICS_CONTROLLER_HOST_NAME: ${APPDYNAMICS_CONTROLLER_HOST_NAME}
      APPDYNAMICS_CONTROLLER_PORT: ${APPDYNAMICS_CONTROLLER_PORT}
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: ${APPDYNAMICS_CONTROLLER_SSL_ENABLED}
      APPDYNAMICS_AGENT_ACCOUNT_NAME: ${APPDYNAMICS_AGENT_ACCOUNT_NAME}
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: ${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: ${APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME}
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX:  ${APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX} 
      APPDYNAMICS_AGENT_APPLICATION_NAME:  ${APPDYNAMICS_AGENT_APPLICATION_NAME}
      APPDYNAMICS_AGENT_TIER_NAME: 'atm'
      APPDYNAMICS_AGENT_NODE_NAME: 'atm01'      

    #APM - ADD AGENT VOLUME
    volumes:
      - otel-agent-volume:/opt/agent
    restart: unless-stopped 

  visa:
    image: leandrovo/digitalbank-backend-java:1.0
    container_name: backends-visa-java
    ports:
      - "10082:8081"
    environment:
      AWS_API_URL: https://pp58dqva7a.execute-api.us-east-1.amazonaws.com/api/

      #APM AGENT VARIABLES
      JAVA_TOOL_OPTIONS: '-javaagent:/opt/agent/opentelemetry-javaagent.jar'
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: service.name=visa,service.namespace=${APPDYNAMICS_AGENT_APPLICATION_NAME}
      APPDYNAMICS_CONTROLLER_HOST_NAME: ${APPDYNAMICS_CONTROLLER_HOST_NAME}
      APPDYNAMICS_CONTROLLER_PORT: ${APPDYNAMICS_CONTROLLER_PORT}
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: ${APPDYNAMICS_CONTROLLER_SSL_ENABLED}
      APPDYNAMICS_AGENT_ACCOUNT_NAME: ${APPDYNAMICS_AGENT_ACCOUNT_NAME}
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: ${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: ${APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME}
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX:  ${APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX}
      APPDYNAMICS_AGENT_APPLICATION_NAME:  ${APPDYNAMICS_AGENT_APPLICATION_NAME}
      APPDYNAMICS_AGENT_TIER_NAME: 'visa'
      APPDYNAMICS_AGENT_NODE_NAME: 'visa-node'      

    #APM - ADD AGENT VOLUME
    volumes:
      - otel-agent-volume:/opt/agent
    restart: unless-stopped     

###########
### LOAD
#########

  jmeter:
    image: leandrovo/jmeter:1.0
    hostname: jmeter
    restart: always
    volumes:
      - ${PWD}/scripts:/opt/jmeter/scripts
    environment:
      BASE_URL_1: "nginx"
      HTTP_PORT: "80"
      USERNAME: "jsmith@demo.io"
      PASSWORD: "Demo123!"
      BASE_URL_API_GATEWAY: "bank"
      BASE_GATEWAY_PORT: "8081"
    depends_on:
      - bank


#APM ADD AGENT VOLUME
volumes:
   agent-volume:
   otel-agent-volume:

